AllCops:
  TargetRubyVersion: 2.3
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
