sudo: false
cache: bundler
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

env:
  - ANDROID_HOME='/tmp' # dummy

script:
  - mkdir /tmp/platform-tools
  - touch /tmp/platform-tools/adb
  - ruby test/run_test.rb
