sudo: false
cache: bundler
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

env:
  - ANDROID_HOME='~' # dummy

script:
  - mkdir ~/platform-tools
  - touch ~/platform-tools/adb
  - ruby test/run_test.rb
